version: "3.3"
services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    privileged: true
    ports: ["8081:80"]
    volumes:
      [
        /Users/pengbin/workspace:/var/www,
        /Users/pengbin/docker/nginx/nginx.conf:/etc/nginx/nginx.conf,
        /Users/pengbin/docker/nginx/conf.d:/etc/nginx/conf.d,
      ]
    working_dir: /var/www
    tty: true
    networks:
      - web-net
  php:
    image: scottpb/php8.1.13:v1.0.2
    container_name: php
    restart: always
    privileged: true
    cap_add: [SYS_PTRACE]
    working_dir: /var/www
    volumes:
      [
        /Users/pengbin/workspace:/var/www,
        /Users/pengbin/docker/php/conf.d:/usr/local/etc/php/conf.d,
      ]
    networks:
      - web-net
  redis:
    image: redis
    restart: always
    container_name: redis
    ports: ["6379:6379"]
    networks:
      - web-net
networks:
  web-net:
